# Generated by Django 5.1.1 on 2024-10-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="buy_ling",
            new_name="buy_link",
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="country",
            field=models.CharField(
                help_text="Country In Capital", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="short_name",
            field=models.CharField(
                help_text="Currency shorthand in UPPERCASE", max_length=3, unique=True
            ),
        ),
    ]
