# Generated by Django 5.1.1 on 2024-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_rename_buy_ling_bank_buy_link_alter_bank_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="buy_link",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="sell_link",
        ),
        migrations.AddField(
            model_name="bank",
            name="forex_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
