# Generated by Django 5.1.1 on 2024-10-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_remove_bank_buy_link_remove_bank_sell_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aggregatorlog",
            name="type",
        ),
    ]
